sudo: true

language: python

python: 3.7

cache:
    - pip

before_install:
    - sudo apt update
    - sudo apt install -y quantum-espresso
    - pip install codecov pytest pytest-cov
    - wget http://folk.uio.no/anjohan/lmp
    - "wget https://github.com/cp2k/cp2k/releases/download/\
      v6.1.0/cp2k-6.1-Linux-x86_64.sopt"
    - chmod u+x lmp
    - chmod u+x cp2k-6.1-Linux-x86_64.sopt
    - pip install -r requirements.txt

script:
    - cd tests
    - PWSCF_COMMAND=pw.x CP2K_COMMAND=../cp2k-6.1-Linux-x86_64.sopt lmp=../lmp
      pytest --cov=../flare/
    - coverage xml

after_success:
    - codecov
